# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: eli-equals-mc-2/WordPuzzleDataset
dataset_train_split: train
dataset_test_split: validation
dataset_num_proc: 4

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: eli-equals-mc-2/Qwen2.5-WordPuzzle-SFT
hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 8192